import {
  Category,
  Generic,
  Supplier,
  Customer,
  Doctor,
  Medicine,
  Batch,
  StockMovement,
  Purchase,
  Sale,
  Expense,
  Prescription,
  OnlineOrder,
  PharmacySettings,
  Notification,
  AuditLog,
} from '../types';

export const initialCategories: Category[] = [
  { id: 'cat-1', name: 'Analgesic & Antipyretic', slug: 'analgesic', description: 'Pain relief and fever reducers', is_active: true },
  { id: 'cat-2', name: 'Antibiotic', slug: 'antibiotic', description: 'Bacterial infection treatments', is_active: true },
  { id: 'cat-3', name: 'Antacid & Antiulcer', slug: 'antacid', description: 'Gastric acid and ulcer care', is_active: true },
  { id: 'cat-4', name: 'Antihistamine', slug: 'antihistamine', description: 'Allergy and cold relief', is_active: true },
  { id: 'cat-5', name: 'Diabetes Care', slug: 'diabetes', description: 'Insulin and oral hypoglycemics', is_active: true },
  { id: 'cat-6', name: 'Blood Pressure & Cardiac', slug: 'cardiac', description: 'Hypertension and heart health', is_active: true },
  { id: 'cat-7', name: 'Vitamins & Supplements', slug: 'vitamins', description: 'Nutritional and multivitamin aids', is_active: true },
  { id: 'cat-8', name: 'Respiratory & Asthma', slug: 'respiratory', description: 'Bronchodilators & inhalers', is_active: true },
  { id: 'cat-9', name: 'Pediatric Care', slug: 'pediatric', description: 'Drops and syrups formulated for children', is_active: true },
  { id: 'cat-10', name: 'Surgical & First Aid', slug: 'surgical', description: 'Bandages, antiseptics, syringes', is_active: true },
];

export const initialGenerics: Generic[] = [
  { id: 'gen-1', name: 'Paracetamol', description: 'Analgesic & antipyretic agent', indication: 'Fever, mild-to-moderate pain, headache', side_effects: 'Rare hepatotoxicity at high doses', status: 'Active' },
  { id: 'gen-2', name: 'Omeprazole', description: 'Proton-pump inhibitor (PPI)', indication: 'GERD, peptic ulcer, acid reflux', side_effects: 'Abdominal pain, headache', status: 'Active' },
  { id: 'gen-3', name: 'Esomeprazole', description: 'S-isomer of omeprazole PPI', indication: 'Erosive esophagitis, Zollinger-Ellison syndrome', side_effects: 'Nausea, flatulence', status: 'Active' },
  { id: 'gen-4', name: 'Ciprofloxacin', description: 'Fluoroquinolone antibiotic', indication: 'Urinary tract infections, respiratory infections', side_effects: 'Tendinitis risk, dizziness', status: 'Active' },
  { id: 'gen-5', name: 'Montelukast', description: 'Leukotriene receptor antagonist', indication: 'Chronic asthma, allergic rhinitis', side_effects: 'Headache, neuropsychiatric events', status: 'Active' },
  { id: 'gen-6', name: 'Metformin Hydrochloride', description: 'Biguanide antihyperglycemic', indication: 'Type 2 diabetes mellitus', side_effects: 'GI upset, lactic acidosis (rare)', status: 'Active' },
  { id: 'gen-7', name: 'Amlodipine', description: 'Dihydropyridine calcium channel blocker', indication: 'Hypertension, coronary artery disease', side_effects: 'Peripheral edema, flushing', status: 'Active' },
  { id: 'gen-8', name: 'Azithromycin', description: 'Macrolide antibiotic', indication: 'Community-acquired pneumonia, strep throat', side_effects: 'Diarrhea, QT prolongation', status: 'Active' },
  { id: 'gen-9', name: 'Cetirizine Hydrochloride', description: 'Second-generation H1 antihistamine', indication: 'Hay fever, urticaria, allergy pruritus', side_effects: 'Mild drowsiness, dry mouth', status: 'Active' },
  { id: 'gen-10', name: 'Vitamin B-Complex', description: 'Essential water-soluble vitamins', indication: 'Nutritional deficiency, fatigue, neuropathy', side_effects: 'Bright yellow urine', status: 'Active' },
];

export const initialSuppliers: Supplier[] = [
  {
    id: 'sup-1',
    name: 'Square Pharmaceuticals Ltd.',
    company: 'Square Group Bangladesh',
    phone: '+880 1711-234567',
    email: 'distribution@squarepharma.com.bd',
    address: 'Square Centre, 48 Mohakhali C/A, Dhaka-1212',
    contact_person: 'Md. Rafiqul Islam (Senior Territory Officer)',
    opening_balance: 0,
    current_balance: 14500,
    notes: 'Primary national distributor, weekly credit limit ৳100,000',
  },
  {
    id: 'sup-2',
    name: 'Beximco Pharmaceuticals Ltd.',
    company: 'Beximco Group',
    phone: '+880 1712-345678',
    email: 'supply@beximcopharma.com',
    address: '19 Dhanmondi R/A, Road 7, Dhaka-1205',
    contact_person: 'Tanvir Hossain (Regional Depot Lead)',
    opening_balance: 0,
    current_balance: 8200,
    notes: 'Direct depot delivery, 15-day credit terms',
  },
  {
    id: 'sup-3',
    name: 'Incepta Pharmaceuticals Ltd.',
    company: 'Incepta Group',
    phone: '+880 1713-456789',
    email: 'sales@inceptapharma.com',
    address: '40 Shahid Tajuddin Ahmed Sarani, Tejgaon I/A, Dhaka-1208',
    contact_person: 'Kamrul Hasan',
    opening_balance: 0,
    current_balance: 0,
    notes: 'High quality biologics and sterile injections',
  },
  {
    id: 'sup-4',
    name: 'Renata Limited',
    company: 'Renata Pharma',
    phone: '+880 1714-567890',
    email: 'orders@renata-ltd.com',
    address: 'Plot # 1, Milk Vita Road, Section-7, Mirpur, Dhaka-1216',
    contact_person: 'Nasim Akhtar',
    opening_balance: 0,
    current_balance: 4200,
    notes: 'Manufacturer of Maxpro and Fexo',
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'Md. Anwar Hossain',
    phone: '01819-123456',
    email: 'anwar.hossain@gmail.com',
    address: 'House 42, Road 11, Banani, Dhaka',
    date_of_birth: '1975-06-15',
    gender: 'Male',
    total_purchases: 8450,
    due_amount: 0,
    notes: 'Regular patient for BP & Diabetes medications',
  },
  {
    id: 'cust-2',
    name: 'Mrs. Rokeya Begum',
    phone: '01712-987654',
    email: 'rokeya.b@yahoo.com',
    address: 'Flat B3, Green Road, Dhanmondi, Dhaka',
    date_of_birth: '1968-11-22',
    gender: 'Female',
    total_purchases: 14200,
    due_amount: 350,
    notes: 'Chronic arthritis patient',
  },
  {
    id: 'cust-3',
    name: 'Shakil Ahmed',
    phone: '01923-456789',
    email: 'shakil.tech@outlook.com',
    address: 'Sector 4, Uttara, Dhaka',
    date_of_birth: '1992-04-10',
    gender: 'Male',
    total_purchases: 3200,
    due_amount: 0,
    notes: 'Online delivery customer',
  },
];

export const initialDoctors: Doctor[] = [
  {
    id: 'doc-1',
    name: 'Prof. Dr. M. A. Jalil',
    specialization: 'Internal Medicine & Cardiology',
    registration_number: 'BMDC-A-24510',
    hospital: 'Dhaka Medical College Hospital',
    phone: '01711-889900',
    email: 'dr.jalil@dmch.gov.bd',
    address: 'Secretariat Road, Dhaka',
  },
  {
    id: 'doc-2',
    name: 'Dr. Farhana Sultana',
    specialization: 'Endocrinology & Diabetology',
    registration_number: 'BMDC-A-38714',
    hospital: 'BIRDEM General Hospital',
    phone: '01819-776655',
    email: 'farhana.endo@birdem.org',
    address: 'Shahbagh, Dhaka',
  },
];

export const initialMedicines: Medicine[] = [
  {
    id: 'med-1',
    name: 'Napa Extra 500mg+65mg',
    generic_id: 'gen-1',
    category_id: 'cat-1',
    brand_name: 'Napa Extra',
    manufacturer: 'Beximco Pharmaceuticals Ltd.',
    dosage_form: 'Tablet',
    strength: '500mg + 65mg',
    unit: 'Strip',
    pack_size: '10 Tablets/Strip',
    barcode: '894123456001',
    sku: 'MED-NAP-EXT',
    prescription_required: false,
    purchase_price: 22.0,
    sale_price: 28.0,
    min_stock: 50,
    reorder_level: 100,
    description: 'Paracetamol with Caffeine for fast headache and fever relief',
    status: 'Active',
  },
  {
    id: 'med-2',
    name: 'Seclo 20mg Capsule',
    generic_id: 'gen-2',
    category_id: 'cat-3',
    brand_name: 'Seclo',
    manufacturer: 'Square Pharmaceuticals Ltd.',
    dosage_form: 'Capsule',
    strength: '20mg',
    unit: 'Strip',
    pack_size: '10 Capsules/Strip',
    barcode: '894123456002',
    sku: 'MED-SEC-020',
    prescription_required: false,
    purchase_price: 48.0,
    sale_price: 60.0,
    min_stock: 40,
    reorder_level: 80,
    description: 'Omeprazole capsule for hyperacidity, peptic ulcer, and heartburn',
    status: 'Active',
  },
  {
    id: 'med-3',
    name: 'Maxpro 20mg Tablet',
    generic_id: 'gen-3',
    category_id: 'cat-3',
    brand_name: 'Maxpro',
    manufacturer: 'Renata Limited',
    dosage_form: 'Tablet',
    strength: '20mg',
    unit: 'Strip',
    pack_size: '14 Tablets/Strip',
    barcode: '894123456003',
    sku: 'MED-MAX-020',
    prescription_required: false,
    purchase_price: 85.0,
    sale_price: 105.0,
    min_stock: 30,
    reorder_level: 60,
    description: 'Esomeprazole magnesium delayed release tablet',
    status: 'Active',
  },
  {
    id: 'med-4',
    name: 'Ciprocin 500mg Tablet',
    generic_id: 'gen-4',
    category_id: 'cat-2',
    brand_name: 'Ciprocin',
    manufacturer: 'Square Pharmaceuticals Ltd.',
    dosage_form: 'Tablet',
    strength: '500mg',
    unit: 'Strip',
    pack_size: '10 Tablets/Strip',
    barcode: '894123456004',
    sku: 'MED-CIP-500',
    prescription_required: true,
    purchase_price: 110.0,
    sale_price: 140.0,
    min_stock: 25,
    reorder_level: 50,
    description: 'Broad-spectrum ciprofloxacin antibiotic for severe infections',
    status: 'Active',
  },
  {
    id: 'med-5',
    name: 'Monas 10mg Tablet',
    generic_id: 'gen-5',
    category_id: 'cat-8',
    brand_name: 'Monas',
    manufacturer: 'The ACME Laboratories Ltd.',
    dosage_form: 'Tablet',
    strength: '10mg',
    unit: 'Strip',
    pack_size: '10 Tablets/Strip',
    barcode: '894123456005',
    sku: 'MED-MON-010',
    prescription_required: true,
    purchase_price: 125.0,
    sale_price: 160.0,
    min_stock: 30,
    reorder_level: 70,
    description: 'Montelukast oral tablets for asthma prevention and seasonal rhinitis',
    status: 'Active',
  },
  {
    id: 'med-6',
    name: 'Comet 500mg Tablet',
    generic_id: 'gen-6',
    category_id: 'cat-5',
    brand_name: 'Comet',
    manufacturer: 'Square Pharmaceuticals Ltd.',
    dosage_form: 'Tablet',
    strength: '500mg',
    unit: 'Strip',
    pack_size: '10 Tablets/Strip',
    barcode: '894123456006',
    sku: 'MED-COM-500',
    prescription_required: true,
    purchase_price: 36.0,
    sale_price: 45.0,
    min_stock: 50,
    reorder_level: 100,
    description: 'Metformin HCl for management of type 2 diabetes mellitus',
    status: 'Active',
  },
  {
    id: 'med-7',
    name: 'Camlodin 5mg Tablet',
    generic_id: 'gen-7',
    category_id: 'cat-6',
    brand_name: 'Camlodin',
    manufacturer: 'Square Pharmaceuticals Ltd.',
    dosage_form: 'Tablet',
    strength: '5mg',
    unit: 'Strip',
    pack_size: '10 Tablets/Strip',
    barcode: '894123456007',
    sku: 'MED-CAM-005',
    prescription_required: true,
    purchase_price: 40.0,
    sale_price: 50.0,
    min_stock: 40,
    reorder_level: 80,
    description: 'Amlodipine besylate for essential hypertension',
    status: 'Active',
  },
  {
    id: 'med-8',
    name: 'Zithrin 500mg Tablet',
    generic_id: 'gen-8',
    category_id: 'cat-2',
    brand_name: 'Zithrin',
    manufacturer: 'Beximco Pharmaceuticals Ltd.',
    dosage_form: 'Tablet',
    strength: '500mg',
    unit: 'Strip',
    pack_size: '6 Tablets/Strip',
    barcode: '894123456008',
    sku: 'MED-ZIT-500',
    prescription_required: true,
    purchase_price: 180.0,
    sale_price: 210.0,
    min_stock: 15,
    reorder_level: 35,
    description: 'Azithromycin macrolide antibiotic strip of 6',
    status: 'Active',
  },
  {
    id: 'med-9',
    name: 'Alatrol 10mg Tablet',
    generic_id: 'gen-9',
    category_id: 'cat-4',
    brand_name: 'Alatrol',
    manufacturer: 'Square Pharmaceuticals Ltd.',
    dosage_form: 'Tablet',
    strength: '10mg',
    unit: 'Strip',
    pack_size: '10 Tablets/Strip',
    barcode: '894123456009',
    sku: 'MED-ALA-010',
    prescription_required: false,
    purchase_price: 24.0,
    sale_price: 30.0,
    min_stock: 40,
    reorder_level: 90,
    description: 'Cetirizine hydrochloride non-sedating antihistamine',
    status: 'Active',
  },
  {
    id: 'med-10',
    name: 'B-50 Forte Tablet',
    generic_id: 'gen-10',
    category_id: 'cat-7',
    brand_name: 'B-50 Forte',
    manufacturer: 'Square Pharmaceuticals Ltd.',
    dosage_form: 'Tablet',
    strength: 'Therapeutic',
    unit: 'Bottle',
    pack_size: '30 Tablets/Bottle',
    barcode: '894123456010',
    sku: 'MED-B50-FOR',
    prescription_required: false,
    purchase_price: 65.0,
    sale_price: 80.0,
    min_stock: 20,
    reorder_level: 40,
    description: 'Therapeutic vitamin B-Complex tablet bottle',
    status: 'Active',
  },
];

// Batches with FEFO test cases:
// Some with earliest expiry, some expiring within 30 days, some expired to enforce validation rules!
export const initialBatches: Batch[] = [
  // Napa Extra Batches (FEFO demonstration)
  {
    id: 'bat-1',
    medicine_id: 'med-1',
    batch_number: 'NP-24A01',
    mfg_date: '2025-01-15',
    expiry_date: '2027-01-14', // Earliest valid batch for Napa
    purchase_price: 22.0,
    sale_price: 28.0,
    quantity: 150,
    remaining_quantity: 85,
    supplier_id: 'sup-2',
    created_at: '2025-01-20T10:00:00Z',
  },
  {
    id: 'bat-2',
    medicine_id: 'med-1',
    batch_number: 'NP-25B02',
    mfg_date: '2025-06-10',
    expiry_date: '2027-06-09', // Later expiry for Napa
    purchase_price: 22.0,
    sale_price: 28.0,
    quantity: 200,
    remaining_quantity: 200,
    supplier_id: 'sup-2',
    created_at: '2025-06-15T11:00:00Z',
  },

  // Seclo 20mg Batches
  {
    id: 'bat-3',
    medicine_id: 'med-2',
    batch_number: 'SC-24K09',
    mfg_date: '2024-11-01',
    expiry_date: '2026-10-31', // Expiring in under 30 days! (Near expiry warning)
    purchase_price: 48.0,
    sale_price: 60.0,
    quantity: 100,
    remaining_quantity: 18,
    supplier_id: 'sup-1',
    created_at: '2024-11-05T09:30:00Z',
  },
  {
    id: 'bat-4',
    medicine_id: 'med-2',
    batch_number: 'SC-25D14',
    mfg_date: '2025-04-10',
    expiry_date: '2027-04-09', // Healthy batch
    purchase_price: 48.0,
    sale_price: 60.0,
    quantity: 120,
    remaining_quantity: 110,
    supplier_id: 'sup-1',
    created_at: '2025-04-12T14:20:00Z',
  },

  // Maxpro 20mg Batches
  {
    id: 'bat-5',
    medicine_id: 'med-3',
    batch_number: 'MX-25A11',
    mfg_date: '2025-02-01',
    expiry_date: '2027-08-31',
    purchase_price: 85.0,
    sale_price: 105.0,
    quantity: 90,
    remaining_quantity: 52,
    supplier_id: 'sup-4',
    created_at: '2025-02-10T10:00:00Z',
  },

  // Ciprocin 500mg Batches (One EXPIRED batch to test "Expired Batch Cannot be sold" rule!)
  {
    id: 'bat-6',
    medicine_id: 'med-4',
    batch_number: 'CP-23X99-EXP',
    mfg_date: '2023-01-10',
    expiry_date: '2025-01-09', // EXPIRED! Must NEVER be sold in POS!
    purchase_price: 105.0,
    sale_price: 135.0,
    quantity: 30,
    remaining_quantity: 12,
    supplier_id: 'sup-1',
    created_at: '2023-01-15T12:00:00Z',
  },
  {
    id: 'bat-7',
    medicine_id: 'med-4',
    batch_number: 'CP-25F18',
    mfg_date: '2025-06-01',
    expiry_date: '2027-05-31', // Valid batch
    purchase_price: 110.0,
    sale_price: 140.0,
    quantity: 60,
    remaining_quantity: 45,
    supplier_id: 'sup-1',
    created_at: '2025-06-05T15:00:00Z',
  },

  // Monas 10mg (Low Stock case: total remaining is only 15, below min_stock of 30)
  {
    id: 'bat-8',
    medicine_id: 'med-5',
    batch_number: 'MN-24H08',
    mfg_date: '2024-08-01',
    expiry_date: '2026-11-15',
    purchase_price: 125.0,
    sale_price: 160.0,
    quantity: 50,
    remaining_quantity: 14, // LOW STOCK TRIGGER!
    supplier_id: 'sup-1',
    created_at: '2024-08-10T11:00:00Z',
  },

  // Comet 500mg
  {
    id: 'bat-9',
    medicine_id: 'med-6',
    batch_number: 'CM-25C03',
    mfg_date: '2025-03-01',
    expiry_date: '2027-03-01',
    purchase_price: 36.0,
    sale_price: 45.0,
    quantity: 150,
    remaining_quantity: 130,
    supplier_id: 'sup-1',
    created_at: '2025-03-05T09:00:00Z',
  },

  // Camlodin 5mg
  {
    id: 'bat-10',
    medicine_id: 'med-7',
    batch_number: 'CD-25E22',
    mfg_date: '2025-05-15',
    expiry_date: '2027-05-14',
    purchase_price: 40.0,
    sale_price: 50.0,
    quantity: 100,
    remaining_quantity: 75,
    supplier_id: 'sup-1',
    created_at: '2025-05-20T10:15:00Z',
  },

  // Zithrin 500mg
  {
    id: 'bat-11',
    medicine_id: 'med-8',
    batch_number: 'ZT-25G10',
    mfg_date: '2025-07-01',
    expiry_date: '2027-06-30',
    purchase_price: 180.0,
    sale_price: 210.0,
    quantity: 40,
    remaining_quantity: 28,
    supplier_id: 'sup-2',
    created_at: '2025-07-05T13:30:00Z',
  },

  // Alatrol 10mg
  {
    id: 'bat-12',
    medicine_id: 'med-9',
    batch_number: 'AL-25B19',
    mfg_date: '2025-02-18',
    expiry_date: '2027-02-17',
    purchase_price: 24.0,
    sale_price: 30.0,
    quantity: 120,
    remaining_quantity: 94,
    supplier_id: 'sup-1',
    created_at: '2025-02-22T16:00:00Z',
  },

  // B-50 Forte
  {
    id: 'bat-13',
    medicine_id: 'med-10',
    batch_number: 'BF-25D04',
    mfg_date: '2025-04-01',
    expiry_date: '2027-03-31',
    purchase_price: 65.0,
    sale_price: 80.0,
    quantity: 50,
    remaining_quantity: 38,
    supplier_id: 'sup-1',
    created_at: '2025-04-05T11:45:00Z',
  },
];

export const initialStockMovements: StockMovement[] = [
  {
    id: 'mov-1',
    medicine_id: 'med-1',
    medicine_name: 'Napa Extra 500mg+65mg',
    batch_id: 'bat-1',
    batch_number: 'NP-24A01',
    movement_type: 'Purchase',
    quantity: 150,
    reference_id: 'pur-1',
    reference_type: 'Purchase',
    notes: 'Initial warehouse intake from Beximco Depot',
    created_by: 'Super Admin',
    created_at: '2025-01-20T10:00:00Z',
  },
  {
    id: 'mov-2',
    medicine_id: 'med-2',
    medicine_name: 'Seclo 20mg Capsule',
    batch_id: 'bat-3',
    batch_number: 'SC-24K09',
    movement_type: 'Purchase',
    quantity: 100,
    reference_id: 'pur-2',
    reference_type: 'Purchase',
    notes: 'Purchased from Square Pharmaceuticals',
    created_by: 'Super Admin',
    created_at: '2024-11-05T09:30:00Z',
  },
];

export const initialPurchases: Purchase[] = [
  {
    id: 'pur-1',
    purchase_number: 'PO-2026-001',
    invoice_number: 'BEX-INV-8910',
    supplier_id: 'sup-2',
    supplier_name: 'Beximco Pharmaceuticals Ltd.',
    purchase_date: '2026-09-28',
    payment_type: 'Bank',
    subtotal: 10500,
    discount: 500,
    vat: 500,
    total: 10500,
    paid_amount: 10500,
    due_amount: 0,
    notes: 'Standard monthly restock order',
    items: [
      {
        medicine_id: 'med-1',
        medicine_name: 'Napa Extra 500mg+65mg',
        batch_number: 'NP-25B02',
        mfg_date: '2025-06-10',
        expiry_date: '2027-06-09',
        quantity: 200,
        free_quantity: 10,
        purchase_price: 22.0,
        sale_price: 28.0,
        discount: 0,
        tax: 0,
        total: 4400,
      },
      {
        medicine_id: 'med-8',
        medicine_name: 'Zithrin 500mg Tablet',
        batch_number: 'ZT-25G10',
        mfg_date: '2025-07-01',
        expiry_date: '2027-06-30',
        quantity: 30,
        free_quantity: 0,
        purchase_price: 180.0,
        sale_price: 210.0,
        discount: 0,
        tax: 0,
        total: 5400,
      },
    ],
    created_by: 'Super Admin',
    created_at: '2026-09-28T11:00:00Z',
  },
];

export const initialSales: Sale[] = [
  {
    id: 'sale-1',
    invoice_number: 'INV-2026-001',
    customer_id: 'cust-1',
    customer_name: 'Md. Anwar Hossain',
    customer_phone: '01819-123456',
    sale_date: '2026-10-06',
    payment_method: 'Cash',
    subtotal: 410,
    discount: 10,
    tax: 20,
    total: 420,
    paid_amount: 420,
    due_amount: 0,
    profit: 90, // (28-22)*5 + (60-48)*5 = 30 + 60 = 90
    cashier_name: 'Super Admin',
    notes: 'Walk-in prescription dispense',
    items: [
      {
        medicine_id: 'med-1',
        medicine_name: 'Napa Extra 500mg+65mg',
        batch_id: 'bat-1',
        batch_number: 'NP-24A01',
        expiry_date: '2027-01-14',
        quantity: 5,
        unit_price: 28.0,
        purchase_price: 22.0,
        discount: 0,
        tax: 0,
        total: 140,
        profit: 30,
      },
      {
        medicine_id: 'med-2',
        medicine_name: 'Seclo 20mg Capsule',
        batch_id: 'bat-3',
        batch_number: 'SC-24K09',
        expiry_date: '2026-10-31',
        quantity: 5,
        unit_price: 60.0,
        purchase_price: 48.0,
        discount: 0,
        tax: 0,
        total: 300,
        profit: 60,
      },
    ],
    created_at: '2026-10-06T14:30:00Z',
  },
];

export const initialExpenses: Expense[] = [
  {
    id: 'exp-1',
    expense_number: 'EXP-2026-001',
    date: '2026-10-01',
    category: 'Rent',
    amount: 25000,
    payment_method: 'Cash',
    description: 'Shop monthly rental payment for October 2026',
    created_by: 'Super Admin',
    created_at: '2026-10-01T10:00:00Z',
  },
  {
    id: 'exp-2',
    expense_number: 'EXP-2026-002',
    date: '2026-10-03',
    category: 'Electricity',
    amount: 4850,
    payment_method: 'bKash',
    description: 'DESCO electricity bill payment',
    created_by: 'Super Admin',
    created_at: '2026-10-03T16:00:00Z',
  },
];

export const initialPrescriptions: Prescription[] = [
  {
    id: 'rx-1',
    customer_id: 'cust-1',
    customer_name: 'Md. Anwar Hossain',
    customer_phone: '01819-123456',
    doctor_name: 'Prof. Dr. M. A. Jalil',
    prescription_date: '2026-10-05',
    status: 'Dispensed',
    notes: 'Hypertension maintenance protocol',
    medicines: [
      { medicine_name: 'Camlodin 5mg', dosage: '1+0+0', duration: '30 days', instructions: 'After breakfast' },
      { medicine_name: 'Seclo 20mg', dosage: '1+0+1', duration: '14 days', instructions: 'Before meals' },
    ],
    created_at: '2026-10-05T11:20:00Z',
  },
];

export const initialOrders: OnlineOrder[] = [
  {
    id: 'ord-1',
    order_number: 'ORD-2026-001',
    customer_name: 'Shakil Ahmed',
    customer_phone: '01923-456789',
    customer_email: 'shakil.tech@outlook.com',
    delivery_address: 'House 14, Road 2, Sector 4, Uttara, Dhaka',
    items: [
      { medicine_id: 'med-1', medicine_name: 'Napa Extra 500mg+65mg', price: 28, quantity: 2, total: 56 },
      { medicine_id: 'med-2', medicine_name: 'Seclo 20mg Capsule', price: 60, quantity: 2, total: 120 },
      { medicine_id: 'med-10', medicine_name: 'B-50 Forte Tablet', price: 80, quantity: 1, total: 80 },
    ],
    subtotal: 256,
    discount: 0,
    delivery_fee: 50,
    total: 306,
    payment_method: 'Cash',
    status: 'Confirmed',
    notes: 'Please call before doorstep arrival',
    created_at: '2026-10-07T08:15:00Z',
  },
];

export const defaultSettings: PharmacySettings = {
  pharmacy_name: 'MediStock Pro Pharmacy & Healthcare',
  tagline: 'Your Trusted 24/7 Digital Pharmacy & Care Partner',
  address: 'Plot 12, Gulshan Avenue, Gulshan-1, Dhaka-1212, Bangladesh',
  phone: '+880 2-9887766 / +880 1700-112233',
  email: 'care@medistockpro.com.bd',
  website: 'https://medistockpro.bd',
  invoice_prefix: 'MS-',
  currency: 'BDT',
  currency_symbol: '৳',
  tax_rate: 5.0, // 5% VAT standard for retail medicines
  low_stock_threshold: 30,
  expiry_warning_days: 60,
  receipt_size: '80mm',
  date_format: 'DD/MM/YYYY',
  timezone: 'Asia/Dhaka',
  language: 'en',
};

export const initialNotifications: Notification[] = [
  {
    id: 'notif-1',
    title: 'Near Expiry Alert',
    message: 'Batch SC-24K09 of Seclo 20mg Capsule is expiring on 31/10/2026 (in < 30 days).',
    type: 'expiry',
    read: false,
    link: '/admin/expiry',
    created_at: '2026-10-07T09:00:00Z',
  },
  {
    id: 'notif-2',
    title: 'Low Stock Alert',
    message: 'Monas 10mg Tablet is below reorder level (14 remaining vs 70 reorder target).',
    type: 'low_stock',
    read: false,
    link: '/admin/low-stock',
    created_at: '2026-10-07T09:15:00Z',
  },
  {
    id: 'notif-3',
    title: 'New Online Order Received',
    message: 'Order #ORD-2026-001 received from Shakil Ahmed (Total: ৳306).',
    type: 'order',
    read: false,
    link: '/admin/sales',
    created_at: '2026-10-07T08:15:00Z',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log-1',
    user_email: 'admin@medistockpro.com',
    user_role: 'Super Admin',
    action: 'System Initialized',
    module: 'System',
    details: 'MediStock Pro Cloud database initialized with default configurations.',
    created_at: '2026-10-07T08:00:00Z',
  },
];

export const initialNotices: any[] = [
  {
    id: 'notc-1',
    title: 'Free Blood Pressure & Glucose Screening Every Friday',
    category: 'Healthcare',
    content: 'Visit our Gulshan branch for free complimentary blood pressure and random blood sugar checkups supervised by registered pharmacists.',
    media_url: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=800&auto=format&fit=crop&q=80',
    media_type: 'photo',
    is_pinned: true,
    is_published: true,
    created_at: '2026-10-05T10:00:00Z',
  },
  {
    id: 'notc-2',
    title: 'Seasonal Dengue Prevention & Hydration Guidelines',
    category: 'Regulatory',
    content: 'Important public health advisory: Use DGDA approved paracetamol only and avoid NSAIDs without doctor consultation during fever.',
    media_url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop&q=80',
    media_type: 'photo',
    is_pinned: false,
    is_published: true,
    created_at: '2026-10-06T12:00:00Z',
  },
  {
    id: 'notc-3',
    title: '10% Cashback on bKash & Nagad Online Payments',
    category: 'Discount & Offer',
    content: 'Get 10% instant discount up to ৳100 on all online medicine deliveries paid via bKash or Nagad.',
    media_url: 'https://images.unsplash.com/photo-1559599101-f09722fb4948?w=800&auto=format&fit=crop&q=80',
    media_type: 'photo',
    is_pinned: false,
    is_published: true,
    created_at: '2026-10-07T09:00:00Z',
  },
];

export const initialMedia: any[] = [
  {
    id: 'med-1',
    title: 'Pharmacy Cleanroom & Cold Storage Facility',
    description: '24/7 temperature monitored vaccines and insulin storage unit.',
    file_url: 'https://images.unsplash.com/photo-1586015555751-63bb77f4322a?w=800&auto=format&fit=crop&q=80',
    media_type: 'photo',
    file_size: 1024000,
    tag: 'Facility',
    uploaded_by: 'Super Admin',
    created_at: '2026-10-05T08:00:00Z',
  },
  {
    id: 'med-2',
    title: 'Certified Model Pharmacy Storefront',
    description: 'Gulshan branch customer reception and automated dispensing counter.',
    file_url: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=800&auto=format&fit=crop&q=80',
    media_type: 'photo',
    file_size: 2048000,
    tag: 'Storefront',
    uploaded_by: 'Super Admin',
    created_at: '2026-10-06T09:00:00Z',
  },
];

